name: Patchwork PRReview

on:
  pull_request:
    branches: [master]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: jwalton/gh-find-current-pr@master
      id: findPr
    
    - name: PR Review
      run: |
        pip install patchwork-cli
        patchwork PRReview --log debug \
        --openai_api_key= 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\
        --github_api_key=${{ secrets.GITHUB_TOKEN }} \
        --pr_url=https://github.com/${{ github.repository }}/pull/${{ steps.findPr.outputs.number }}
