name: Patchwork PRReview

on:
  pull_request:
    branches: [main]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: jwalton/gh-find-current-pr@master
      id: findPr
    
    - name: PR Review
      run: |
        pip install patchwork-cli
        patchwork PRReview --log debug \
        --openai_api_key= \
        --github_api_key=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 \
        --pr_url=https://github.com/${{ github.repository }}/pull/${{ steps.findPr.outputs.number }}
